services:
  backend-api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./chat-docs-432213-1d571c2cb42f.json:/app/chat-docs-432213-1d571c2cb42f.json  
    environment:
      FLASK_ENV: production
      PYTHONUNBUFFERED: 1
      GOOGLE_APPLICATION_CREDENTIALS: "/app/chat-docs-432213-1d571c2cb42f.json"
    command: waitress-serve --host 0.0.0.0 --port 5000 app:app
