services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: production
      PYTHONUNBUFFERED: 1
      FLASK_RUN_HOST: 0.0.0.0   
      FLASK_RUN_PORT: 5000
    env_file:
      - .env
    command: waitress-serve --host 0.0.0.0 --port 5000 app:app
