[project]
name = "flask-app"
version = "0.1.0"
description = "A simple Flask application."

readme = "README.md"
requires-python = ">=3.10"

[project.dependencies]
dependencies = "requirements.txt"

[project.optional-dependencies]
dev-requirements = {file = "dev-requirements.txt"}
