services:
  - type: web
    name: chat-docs              
    runtime: docker
    dockerfilePath: ./flask-template/Dockerfile
    repo: https://github.com/Lokesh-DataScience/Chat-DOCs
    plan: free                     
    envVars:
      - key: GOOGLE_API_KEY        
        value: YOUR_GOOGLE_API_KEY
      - key: SECRET_KEY
        value: "your_flask_secret_key"
    region: oregon           
    branch: master
    autoDeploy: true            
    healthCheckPath: /
    env: docker
